version: "3.4"
services:

# ##########################################################################
# MOADSD-NG Server
# ##########################################################################
  moadsd-ng-server:
    container_name: moadsd-ng-server
    # image: moadsd-ng-server:latest
    build:
      context: .
      args:
        uid: 1001
        gid: 1001
    volumes:
      - ./workdir:/home/ansible
    environment:
      - TZ=Europe/Berlin
      - DEBIAN_FRONTEND=noninteractive
    stdin_open: true
    tty: true
    restart: always
    network_mode: host
