version: "3.4"
services:

# ##########################################################################
# MOADSD-NG Server
# ##########################################################################
  moadsd-ng-server:
    container_name: moadsd-ng-server
    build:
      context: .
      args:
        uid: ${UID}
        gid: ${GID}
    volumes:
      - ./workdir:/home/ansible
    environment:
      - TZ=Europe/Berlin
      - DEBIAN_FRONTEND=noninteractive
    stdin_open: true
    tty: true
    restart: always
    network_mode: host

# docker build --build-arg uid=$(id -u) --build-arg gid=$(id -g) -t moadsd-ng-server -f Dockerfile .
