version: "3.7"
services:

# ##########################################################################
# MOADSD-NG Server
# ##########################################################################
  moadsd-ng-server:
    container_name: moadsd-ng-server
    # image: moadsd-ng-server:latest
    build:
      context: .
      args:
        uid: 1001
        gid: 1001
    volumes:
      - /home/ansible/moadsd-ng-workdir/moadsd-ng:/home/ansible/moadsd-ng
      - /home/ansible/moadsd-ng-workdir/ansible.json:/home/ansible/ansible.json
      - /home/ansible/moadsd-ng-workdir/.vault-pass.txt:/home/ansible/.vault-pass.txt
      - /home/ansible/moadsd-ng-workdir/.aws:/home/ansible/.aws
      - /home/ansible/moadsd-ng-workdir/.config:/home/ansible/.config
      # - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      - TZ=Europe/Berlin
      - DEBIAN_FRONTEND=noninteractive
    stdin_open: true
    tty: true
    restart: always
    network_mode: host
