version: "3.7"
services:

# ##########################################################################
# MOADSD-NG Server
# ##########################################################################
  moadsd-ng-server:
    container_name: moadsd-ng-server
    # image: moadsd-ng-server:latest
    build:
      context: .
      args:
        uid: 1001
        gid: 1001
    volumes:
      - ./workdir/moadsd-ng:/home/ansible/moadsd-ng
      - ./workdir/ansible.json:/home/ansible/ansible.json
      - ./workdir/.vault-pass.txt:/home/ansible/.vault-pass.txt
      - ./workdir/.aws:/home/ansible/.aws
      - ./workdir/.config:/home/ansible/.config
      - ./workdir/.ssh/moadsd-ng:/home/ansible/.ssh/moadsd-ng
      - ./workdir/.ssh/id_rsa:/home/ansible/.ssh/id_rsa
      - ./workdir/.ssh/id_rsa.pub:/home/ansible/.ssh/id_rsa.pub
      # - type: bind
      #   source: /etc/timezone
      #   target: /etc/timezone
      #   read_only: true
    environment:
      - TZ=Europe/Berlin
      - DEBIAN_FRONTEND=noninteractive
    stdin_open: true
    tty: true
    restart: always
    network_mode: host
